name: Reviewer Lottery

on:
  pull_request:
    types: [opened, reopened, ready_for_review]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewers
        uses: dearrrfish/reviewer-lottery-with-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          add_reviewers: true
          min_reviewers: 1
          max_reviewers: 3
          default_reviewers: "xerxes-on"
