name: Deploy to cPanel

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, pdo_mysql

      - name: Install Composer dependencies
        run: composer install --no-dev --optimize-autoloader --no-interaction

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install NPM dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments
        with:
          switches: -avz --delete
          path: ./
          remote_path: bookrating.anvarcontact.uz/
          remote_host: ${{ secrets.SSH_HOST }}
          remote_user: ${{ secrets.SSH_USERNAME }}
          remote_key: ${{ secrets.KEY }}   # private key
          remote_port: ${{ secrets.SSH_PORT }}
          exclude: |
            .git*
            node_modules/
            tests/
            storage/
            vendor/
            .env*


      - name: Run post-deployment commands via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          passphrase: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd bookrating.anvarcontact.uz
            composer i --no-dev --optimize-autoloader --no-interaction
            php artisan migrate --force
            php artisan storage:link
            php artisan optimize
            php artisan cache:clear
            php artisan config:clear
            php artisan config:cache
            php artisan route:clear
            php artisan route:cache
            php artisan view:cache
